### ISSUE TITLE
Unable to package (with workaround)

### ISSUE THREAD

**Issue by scoutchorton** [ItsMajestiX/VSCode-Ti#1]
## System

**Operating System**: Ubuntu 18.04
**npm**: 3.5.2
**Node.js**: 12.4.0
**Electron**: 6.1.5
**Visual Studio Code**: 1.41.1
_Not sure how much of this is needed, but it is the environment used when getting this error._

## Steps to reproduce

1. Clone repo and enter directory
2. `npm i`
3. `vsce package`

Output:
```
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-ti@0.0.1 vscode:prepublish /home/scoutchorton/Downloads/VSCode-Ti
> webpack --mode production

Hash: c24b17721e9523a72d48
Version: webpack 4.41.5
Time: 8395ms
Built at: 01/08/2020 11:49:44 PM
           Asset      Size  Chunks                   Chunk Names
    extension.js   806 KiB       0  [emitted]        main
extension.js.map  1.36 MiB       0  [emitted] [dev]  main
Entrypoint main = extension.js extension.js.map
 [0] external "vscode" 42 bytes {0} [built]
 [1] external "fs" 42 bytes {0} [built]
 [2] external "path" 42 bytes {0} [built]
 [4] ./src/extension.ts 2.75 KiB {0} [built]
 [5] ./src/commands.ts 2.07 KiB {0} [built]
 [6] external "util" 42 bytes {0} [built]
 [7] ./src/extutil.ts 808 bytes {0} [built]
[12] ./src/tivars_test/tivars_test.js 1.01 MiB {0} [built]
[13] external "crypto" 42 bytes {0} [optional] [built]
    + 5 hidden modules
 ERROR  SVGs are restricted in README.md; please use other file image formats, such as PNG: https://github.com/ItsMajestiX/VSCode-Ti/workflows/CI/badge.svg
```

## Workaround/Fix

* Remove the first two lines of `readme.md` that cause the issue.
* Repeat steps above, and the package successfully packages (that's an odd sentence).

## Other comments

* Would it be possible to include details about how to use the extension? I got the file formatting to work, but not sure what to do with the extension after that. I have spasm for an assembler and can manage from there, but what else can this do?
* Update `readme.md` with install instructions.
* Package and use Github's nice feature of releases.

Thank you for your time.
\- scoutchorton

**Comment by willem640** [comment]
It packages fine for me, has this been solved?

**Comment by ItsMajestiX** [comment]
Yes, the error above is because VSCE doesn't allow SVGs from non-approved sources, and I guess github actions was an unapproved source at the time. If you aren't getting the error, it must be allowed now. I made a fork of VSCE that you can use if you are still getting that error: https://github.com/ItsMajestiX/vscode-vsce

**Comment by willem640** [comment]
Great!
